codesydney/migram-frontend

src/features/CustomerSignupPage/api/effects.tsx, src/features/CustomerSignupPage/components/CustomerSignupPage.tsx
Adds createSetupIntent and confirmCardSetup (with dummy credit card) to the Customer Onboarding Page.
Fixes #65 as Customers with no payment methods could not accept offers.
=> Fix 65 - Customers Cannot Accept an Offer

.env.development, GETTING_STARTED.md, src/pages/_app.tsx
Add Stripe Publishable Key Env Variable to allow for the developer to use their own Stripe account for local testing.
Fixes #74 
You'll need to add this as an environment variable to the Vercel deployment for the changes to work.
`NEXT_PUBLIC_STRIPE_PK=pk_test_51IyV4OFAD84FX6wfbxzuc1uNnh41w0BfoHKLumVTzCXzUSxFG6S5fly3Ry1Xl0kmpb8JoJD5IriwjC0cDO2Zf49W00NE4Gmy9S`
=> Add Stripe Publishable Key Env Var

src/components/tasks/TaskDetails/TaskDetails.tsx
Temporarily hides the confirm payment button as payments have been disabled until after the soft-launch
fixes #83
=> fix: 83 Hide Confirm Payment Button

src/pages/index.tsx
Hides the "Post a Job" button when the user is not logged in.
fixes: #80
=> fix: 80 Hide "Post a Job" Button If Not Logged In

src/pages/api/auth/[...nextauth].ts
next-auth v4 will throw an error if NEXTAUTH_SECRET is not provided.
See: https://next-auth.js.org/configuration/options#secret
=> fix: broken login due to next-auth update to v4

src/pages/login.tsx
Set JWT as the default auth header for all axios requests. 
Fixes [#105](https://github.com/codesydney/migram-frontend/issues/105)
=> Set JWT as default axios header

src/components/common/UserIcon.tsx
Removes the default `Authorization` header when the user signs out.
Context:
The LoginPage sets a default header when the user logs in.
=> refactor: remove default Auth header upon signout

src/components/common/Header/NavMenu.tsx
This fixes an issue when requests after the user refreshes their browser return HTTP 401. This is caused by the JWT is not being saved as the axios default 'Authorization' header.
=> refactor: NavMenu sets JWT when user refreshes

src/pages/offers.tsx, src/pages/tasks/index.tsx
Protect `/tasks` from being accessed by Service Providers, and protect `/offers` from being accessed by Customers
Closes #147 
**Offers Page when the User is a Customer**
**Tasks Page when the User is a Service Provider**
=> feat: protect /tasks and /offers page

src/common/ApiResponse/createApiResponse.ts, src/common/ApiResponse/index.ts, src/common/ApiResponse/tests/createApiResponse.test.ts, src/common/ApiResponse/tests/utils/isErrorStatusCode.test.ts, src/common/ApiResponse/types.ts, src/common/ApiResponse/utils.ts
This feature translates Axios responses to an ApiResponse which will be used to generate UI Toasts & Notifications.
- add `ApiEvent `& `ApiResponse` type definitions
- add `createApiResponse` function
- add `isStatusCode` util function
=> feat: createApiResponse

package-lock.json, package.json, src/common/ApiResponse/ApiEventsContext.tsx, src/pages/_app.tsx
The `ApiEventsContext` uses the `ImmutableMap` to store a collection of `ApiEvents`. This setups the data structure for the upcoming `Notifications` feature.
Note: I wrote the `map-immute` package specifically for this purpose.
=> feat: add ApiEventsContext

package-lock.json, package.json, src/common/ApiResponse/ApiEventsContext.tsx, src/common/ApiResponse/createApiResponse.ts, src/common/ApiResponse/tests/ApiEventsProvider.test.tsx, src/common/ApiResponse/tests/createApiResponse.test.ts, src/common/ApiResponse/types.ts, src/components/PageWithNotifications.tsx, src/components/tests/PageWithNotifications.test.tsx, src/domains/billing/Checkout/hooks/useTaskFetch.tsx, src/domains/tasks/ViewOffers/api/index.tsx, src/domains/tasks/ViewOffers/components/ViewOffersPage.tsx, src/domains/tasks/ViewOffers/components/test/ViewOffersPage.test.tsx, src/mocks/handlers.ts, src/mocks/handlers/offers.handler.ts, src/mocks/handlers/tasks.handler.ts, tsconfig.json
This pull request adds functionality to handle the state management of API events. 
The following changes were made:
- added a new `apiEventsReducer` for the `apiEventsContext` to manage API request events and store their status
- added implementation in `ViewOffersPage` to handle failed Axios requests and update the relevant `apiEvent` status in the `apiEventsContext`
The `apiEventsReducer` provides centralized management of API request events, allowing the Application to display notifications to the user. 
The ViewOffersPage component now handles failed Axios requests by updating the apiEvents state. This establishes a proof of concept pattern which can be used throughout the entire application.
https://www.loom.com/share/877f51d1eade4cdf884bf7da9314e01b
[View Offers Page with …
=> feat: Notifications [Proof of Concept]

src/domains/tasks/CreateTask/types.tsx, src/domains/tasks/ViewTasks/components/TasksPage.tsx, src/domains/tasks/common/types/index.tsx
Changes:
Separate `PaymentStatusSchema` from `TaskStatusSchema`
Add `paymentStatus` as part of `TaskSchema`
Update the logic of showing checkoutButton
=> Hide Finalize Payment Button on the Tasks Page

src/components/Navigation.tsx, src/components/TopBar.tsx
This pull request adds navigation so that mobile users can navigate between different pages.
And unifies the Desktop menus with the newly added Mobile menus.
[Provider View Desktop](https://user-images.githubusercontent.com/8443215/224527728-6fb32b24-5998-4b48-9b18-7f408bcc5ba9.png)
[Provider View Mobile](https://user-images.githubusercontent.com/8443215/224527786-32a006cb-1bf3-4f00-b5d0-d426d65d0709.png)
[Customer View Desktop](https://user-images.githubusercontent.com/8443215/224527729-ac0b1f0f-d300-4412-9331-91ffbe091bea.png)
[Customer View Mobile](https://user-images.githubusercontent.com/8443215/224527732-fe0f265a-6962-4800-a36c-c156b8f52671.png)
=> feat: Display Different Menus to Different User Types

src/domains/users/ProviderSignUp/hooks/useProviderSignUpForm.tsx, src/domains/users/common/api/index.tsx
This issue was caused by a race condition in the signIn function, which would return before fully resolving. Which resulted in an old JWT token being sent to the backend instead of a new token.
For context:
- User signs up as Provider
- We create a Migram User: `POST /users`
- The we request for a redirect link to the Stripe Connect Onboarding link. <-- this is where the old JWT was sent
- Backend creates new Stripe Account and updates user based on the JWT user.
=> fix: providers signup not updating correct details to user documents

src/common/features/notifications/components/PageWithNotifications.tsx
This pull request adds implementation to render a Toast components based on the Notifications API.
[Mobile Screenshot](https://user-images.githubusercontent.com/8443215/225839014-ab67957e-777e-4b08-b490-61662739d4eb.png)
To test the feature, you will have to navigate to the  ClientProviders file and add the following inititalState prop. This will cause the application to render an Error Toast component.
```tsx
// src/components/ClientProviders.tsx
initialState={[
[
"key",
{
id: "key",
isError: true,
title: "Something went wrong.",
type: "toast",
status: "critical",
source: "test",
} as const,
],
]}
```
=> feat: add Toast notifications

src/components/FormPaddingDiv.tsx, src/domains/tasks/CreateTask/components/CreateTaskPage.tsx, src/domains/users/CustomerSignUp/components/SignUpPage.tsx, src/domains/users/Login/LoginPage.tsx, src/domains/users/ProviderSignUp/components/ProviderSignUpPage.tsx
This commit adds styling that fixes the follow forms from overflowing on mobile viewports:
- Login
- Customer Signup Page
- Provider Signup Page
- Create Task Page
[Mobile Before](https://user-images.githubusercontent.com/8443215/225859204-43cf2ff4-31ea-4dc5-a2a5-b0e75c2ea4e0.png)
[Mobile After](https://user-images.githubusercontent.com/8443215/225858887-b19089fa-ca94-41d9-90c0-67dc29463040.png)
[Mobile Before](https://user-images.githubusercontent.com/8443215/225859213-68aba1f0-f654-4187-abd3-e955d1cddf6b.png)
[Mobile After](https://user-images.githubusercontent.com/8443215/225859044-66228289-223b-4e4a-947e-8d8fa81fe90c.png)
[Mobile Before](https://user-images.githubusercontent.com/8443215/225859221-29f48d55-2c4b-47e6-b64b-96891dd5d508.png)
[Mobile …
=> fix: form styling

src/common/features/notifications/components/PageWithNotifications.tsx, src/common/features/notifications/hooks/NotificationsContext.tsx, src/domains/billing/Checkout/components/CheckoutForm.tsx, src/domains/billing/Checkout/hooks/useCheckoutTaskFetch.tsx, src/domains/tasks/CreateTask/hooks/useCreateTaskForm.tsx, src/domains/tasks/MakeOffer/components/MakeOfferForm.tsx, src/domains/tasks/MakeOffer/components/MakeOfferModal.tsx, src/domains/tasks/ViewListings/components/ListingsPage.tsx, src/domains/tasks/ViewOffers/api/index.tsx, src/domains/tasks/ViewOffers/components/ViewOffersPage.tsx, src/domains/tasks/ViewTasks/api/index.tsx, src/domains/tasks/ViewTasks/components/OffersTable.tsx, src/domains/tasks/ViewTasks/components/TasksPage.tsx, src/domains/users/CustomerSignUp/hooks/useSignUpForm.tsx, src/domains/users/Login/LoginPage.tsx, src/domains/users/ProviderSignUp/hooks/useProviderSignUpForm.tsx, src/domains/users/common/api/index.tsx
This pull request adds implementation that renders Notification Banners or Toasts depending on a HTTP request response.
[Listings (Mobile) - Tasks Failing to Load](https://user-images.githubusercontent.com/8443215/226086244-5dc6e606-251f-4e54-9300-687cdcd3695a.png)
[Make an Offer Modal (Mobile) - Invalid Offer amount](https://user-images.githubusercontent.com/8443215/226086259-7ae68b50-8b07-4a3b-870a-468f3dba2580.png)
[Sign Up Form (Mobile) - Missing Input](https://user-images.githubusercontent.com/8443215/226086286-840843d4-24b4-4157-9f8a-577a17e2616b.png)
[Successful Signup (Mobile)](https://user-images.githubusercontent.com/8443215/226086287-28e906bf-6afa-4425-9250-58985d7c918e.png)
[Successful Login (Mobile)](https://user-images.githubusercontent.com/8443215/226086318-54a7db76-8b73-4c2 …
=> Feat: Handle API Results via the NotifcationsContext

src/domains/tasks/ViewListings/components/ListingsPage.tsx, src/domains/tasks/ViewOffers/api/index.tsx, src/domains/tasks/ViewOffers/components/OfferCard.tsx, src/domains/tasks/ViewOffers/components/TaskCard.tsx, src/domains/tasks/ViewOffers/components/ViewOffersPage.tsx, src/domains/tasks/ViewOffers/components/test/ViewOffersPage.test.tsx, src/domains/tasks/common/api/index.ts, src/mocks/handlers/offers.handler.ts, src/pages/index.tsx, src/pages/offers.tsx, src/pages/tasks/index.tsx
This pull request moves initial fetch requests to server-side for the `ListingsPage` and the `ViewOffersPage`
Changes:
- replace client-side initial `Tasks` fetch for the `ListingsPage` with fetch in `getServerSideProps`
- replace client-side initial `Offers` fetch for the `ViewOffersPage` with fetch in `getServerSideProps`
- refactor: colocate TaskPage fetch handling into `src/domains/tasks/common/api`
- refactor: simplify implementation for the ViewOffersPage and related components
=> feat: move fetch requests to server side

src/domains/tasks/common/types/index.tsx
Rename `Lawn Mowing` Task category to `Other`.
Closes #199
We can add filtering in the future, but it won't block the launch. We'll park filtering for now.
=> feat: rename Lawn Mowing Task category to Other
