components/tasks/CreateTask/SubmitForm.tsx
Changed the icons for submit task page to be the same as the icons in the offer page
=> change create task icons

components/common/ImageModal.tsx, components/tasks/ViewTask/SingleTask.tsx, package-lock.json
Added image modal component to "my tasks". feedback welcome.
Created new ImageModal component which should be reusable for all types of image popup needs.
=> Imagemodal

components/account/CustomerOnboard.tsx, components/common/SuccessMessage.tsx
Resolved issue #31 and issue #27 
- Created a reusable `SuccessMessage` component
- Applied it to the Become a Customer flow
- Refactored to `async await` for easier control over asynchronous functionalities
=> Created success msg component and added it to become a customer confirmation

components/account/AddCard.tsx, components/account/CustomerOnboard.tsx, components/styles/ButtonStyles.tsx, lib/wait.tsx
=> Added confirmation and error messages when adding credit card

GETTING_STARTED.md
Adds a Getting Started file to assist with onboarding new developers to the team.
=> Add GETTING_STARTED.md

components/common/Header.tsx
fixes #48
Credit to [@MReyna12](https://github.com/MReyna12)
=> fix: 48 Signup Button Cannot Be Clicked

components/common/Header.tsx, components/common/NavItems.tsx, package-lock.json
Here goes my first contribution to a project, I hope I made everything right.
Fixes #59
=> navbar-center-intens

package-lock.json, package.json, pages/test-onboard.tsx, src/features/CustomerSignupPage/api/CustomerSignupReducer.tsx, src/features/CustomerSignupPage/api/effects.tsx, src/features/CustomerSignupPage/api/index.tsx, src/features/CustomerSignupPage/components/CustomerSignupForm.tsx, src/features/CustomerSignupPage/components/CustomerSignupPage.tsx, src/features/CustomerSignupPage/components/Notification.tsx, src/features/CustomerSignupPage/index.tsx, src/features/CustomerSignupPage/types/index.tsx
Consolidates the Signup Form and the "Become a Customer" Form.
The form can be accessed via the /test-onboard endpoint.
Also adds Success & Error Notifications. These can be refactored out and used in the rest of the application.
Dependencies Added:
- react-hook-form for form managment
- zod & @hookform/resolvers for input validation
- react-icons
=> feat: CustomerSignupPage

src/pages/provider-signup.tsx, src/pages/signup.tsx, src/pages/test-onboard.tsx
- Move the original Signup Page from /signup to /provider-signup
- Move the new Consolidated Customer from /test-onboard to /signup
=> 70 & 71 Move Signup Pages

src/components/tasks/TaskDetails/TaskDetails.tsx, src/components/tasks/TaskList/FilterTasks.tsx, src/components/tasks/TaskList/TaskCard.tsx, src/components/tasks/TaskList/TasksList.tsx, src/components/tasks/TasksDashboard.tsx
Fixes #77 and allows task filters to correctly filter tasks.
This was achieved by "lifting state up" from the TaskList component to the TaskDetails component.
=> Fix Task Filters Not Working

src/features/CustomerSignupPage/components/CustomerSignupPage.tsx, src/features/CustomerSignupPage/components/Notification.tsx
- Adds a redirect to Home after a customer signs up.
- Adds a "Redirecting to Home" message to the Success Notification.
fixes: #79
=> feat: Add Redirect After Customer Signup

src/components/tasks/CreateTask/sections/Section1.tsx, src/components/tasks/TaskList/FilterTasks.tsx
I'm going to merge these in to make it easy for me to manage different branches.
They were small changes and should have a small footprint.
=> merge dev into main

jest.config.js, package-lock.json, package.json, src/test/global-setup.ts
**Added dependencies**
- @testing-library/jest-dom
- @testing-library/react
- @testing-library/user-event
- jest-environment-jsdom
- msw
- next-router-mock
**And setup configs for jest**
Closes #99
=> build: setup test dependencies

package-lock.json, package.json, public/mockServiceWorker.js, src/components/common/tests/TextInput.test.tsx, src/features/Checkout/CheckoutDetails.tsx, src/features/Checkout/CheckoutForm.tsx, src/features/Checkout/CheckoutPage.tsx, src/features/Checkout/hooks/index.tsx, src/features/Checkout/hooks/useTaskFetch.tsx, src/features/Checkout/index.tsx, src/features/Checkout/tests/CheckoutForm.test.tsx, src/features/Checkout/tests/CheckoutPage.test.tsx, src/mocks/handlers.ts, src/mocks/handlers/tasks.handler.ts, src/pages/checkout/[taskId].tsx, src/test/pages/checkout/[taskId].test.tsx, src/test/utils.tsx, src/types/task.ts, src/utils/FeatureFlag/index.test.tsx
Adds CheckoutPage without the Stripe payment element.
- Registered 'public' folder with MSW
- Fixes MSW getTasks Handler URL
- Adds new Typography styles as the original styles have weird sizes
**Dependencies Added**
- node-fetch & @types/node-fetch as Jest requires a polyfill for fetch
=> feat: Checkout

src/features/Offers/Offer.tsx, src/features/Offers/Offers.tsx, src/features/Tasks/CreateTask/SubmitForm.tsx, src/features/Tasks/TaskDetails/Offer.tsx, src/features/Tasks/TaskDetails/TaskDetails.tsx, src/features/Tasks/TasksDashboard.tsx, src/pages/account/customer/addcard.tsx, src/pages/account/index.tsx, src/pages/login.tsx
Remove the unnecessary calls to useSession in the codebase. As discussed in [#106](https://github.com/codesydney/migram-frontend/issues/106)
Axios already has a default header auth JWT token (see [#108](https://github.com/codesydney/migram-frontend/pull/108))
=> Remove unnecessary calls to useSession for axios

src/middleware.ts
Allows pages to be protected if the User is not logged in.
=> feat: add authentication wall

src/features/Accounts/components/ManageBillingButton.tsx, src/features/Accounts/index.tsx, src/features/Accounts/test/ManageBillingButton.test.tsx, src/pages/account/v2.tsx, src/test/pages/account/v2.test.tsx
Integrates the Stripe Customer Portal to the project, allowing the User to add/edit payment methods, along with editing billing details.
Note: requires an update to the backend as well.
https://www.loom.com/share/612e7f6dc5974719b5d4d3f5ee745bbe
1. Run the project on your local machine (the page is Feature Flagged and will not work on Prod environments).
2. Login with a Customer account
3. Navigate to `/account/v2`
4. Click on the `Manage Billing` button.
=> feat: Stripe Customer Portal Integration

src/features/Checkout/CardElement.tsx, src/features/Checkout/CheckoutForm.tsx, src/features/Checkout/CheckoutPage.tsx, src/features/Checkout/api/createPaymentIntent.tsx, src/features/Checkout/api/index.tsx, src/features/Checkout/hooks/index.tsx, src/features/Checkout/hooks/useCreatePaymentIntent.tsx, src/features/Checkout/tests/CheckoutForm.test.tsx
Adds further integration with Stripe to the CheckoutForm
=> feat: CheckoutPage

src/v2/components/Select.tsx, src/v2/components/index.tsx
Adds a Select component that wires up react-hook-form to Polaris' Select
=> feat: Select component

src/domains/tasks/ViewTasks/components/TasksPage.tsx, src/domains/tasks/ViewTasks/components/tests/OffersTable.test.tsx
This pull request adds additional behaviours to the OfferTable.
This will be the last batch of TDD for this project.
As per our meeting and the upcoming deadlines, I will more to a test-after approach in order to move faster.
=> feat:tasks page - part 3

src/domains/tasks/ViewListings/components/ListingCard.tsx, src/domains/tasks/ViewTasks/components/OffersSection.tsx, src/domains/tasks/ViewTasks/components/TasksPage.tsx, src/domains/tasks/ViewTasks/components/tests/OffersSection.test.tsx, src/domains/tasks/ViewTasks/components/tests/OffersTable.test.tsx, src/domains/tasks/common/components/OfferStatusBadge.tsx, src/domains/tasks/common/components/TaskStatusBadge.tsx, src/domains/tasks/common/components/index.tsx, src/domains/tasks/common/types/index.tsx
- Add badge to TaskCard & Offers to indicate Task/Offer Status.
- Fix failed tests due to refactor and outdated import statements.
Related Issue: #133
Related PRs: #132, #135, #136, #137
=> feat: Tasks Page - part 5

src/domains/tasks/ViewOffers/components/TaskCard.tsx, src/domains/tasks/ViewOffers/components/ViewOffersPage.tsx, src/domains/tasks/ViewTasks/components/OffersTable.tsx, src/domains/tasks/ViewTasks/components/TasksPage.tsx, src/domains/tasks/ViewTasks/components/tests/OffersSection.test.tsx, src/domains/tasks/ViewTasks/components/tests/OffersTable.test.tsx
- refactor TaskCard and OfferTables to separate files
- lazy load components to improve performance
=> refactor: TaskCard and OffersTables

.env.example, src/domains/billing/Checkout/api/createPaymentIntent.tsx
Fix createPaymentIntent to reflect the backend endpoint being protected from unauthorized users.
=> fix: createPaymentIntent return HTTP 401

src/domains/tasks/ViewListings/components/ListingsPage.tsx
As discussed, I removed the three word-break stylings
=> Fix/no session notification add space&margin

src/domains/tasks/ViewListings/components/ListingsPage.tsx
ListingsPage checks isCustomer and only shows button if true NO TESTI…NG at this point
=>  Hide “Create a Task” Button for Providers
